/**
 * C12 — Canonical-YAML golden bytes (team-contracts §1; rework round 2, T2B-R1-F1).
 *
 * The §1 serialization is pinned by HAND-AUTHORED golden byte fixtures: every
 * expected document below was written out by hand from the frozen §1 rules
 * (Unicode CODE-POINT key order at every level, block style, 2-space indent,
 * plain scalars where legal otherwise DOUBLE-quoted, UTF-8, LF, exactly one
 * trailing newline) — NOT generated by either serializer. Both the runtime
 * implementation (src/modules/teams/workflows/canonical-hash.ts) and the
 * independent reference implementation (tests/contracts/_helpers.ts) must
 * reproduce these bytes exactly; agreeing with each other is NOT enough.
 *
 * Includes the two G-lane review probes as permanent regressions:
 *  - UTF-16-vs-codepoint probe: U+E000 must serialize BEFORE U+1F4A9 (the
 *    UTF-16 code-unit sort js-yaml's sortKeys uses gets this backwards);
 *  - quote-style probe: the non-plain scalar `a # b` must be DOUBLE-quoted
 *    (js-yaml's default fallback single-quotes it).
 *
 * The file is pure ASCII on purpose: the probe characters are constructed from
 * their code points so the fixture bytes are unambiguous in review.
 */

import * as yaml from "js-yaml";

import {
  requireContractModule,
  canonicalYaml as referenceCanonicalYaml,
  sha256,
  selfRefHash,
} from "./_helpers";

const HASH_MODULE = "src/modules/teams/workflows/canonical-hash";
const LANE = "T2b-unbounded-team-composer";

const runtime: any = requireContractModule(HASH_MODULE, LANE);

/** U+E000 (private use, BMP) — UTF-16 code unit 0xE000. */
const PUA = String.fromCodePoint(0xe000);
/** U+1F4A9 (astral) — UTF-16 lead surrogate 0xD83D, so it UTF-16-sorts BEFORE U+E000. */
const ASTRAL = String.fromCodePoint(0x1f4a9);
/** U+0080 (C1 control) — not YAML-printable; must take the \x80 escape. */
const C1 = String.fromCodePoint(0x80);

// ── Fixture A — the review probe document (astral/PUA keys + ` # ` scalar) ───

// Insertion order deliberately NOT sorted; both keys are non-ASCII printable.
const A_VALUE: Record<string, string> = {
  [ASTRAL]: "astral",
  note: "a # b",
  [PUA]: "private use",
};

// HAND-AUTHORED: code-point order is note (U+006E...) < U+E000 < U+1F4A9;
// `a # b` carries " #" so it takes the double-quoted fallback.
const GOLDEN_A = `note: "a # b"\n${PUA}: private use\n${ASTRAL}: astral\n`;

// ── Fixture B — scalar styles (ambiguity => double-quoted fallback) ──────────

const B_VALUE: Record<string, unknown> = {
  yes_string: "yes",
  plain: "worker",
  version_like: "007",
  float_like: "1.5e3",
  date_like: "2026-07-30",
  tilde: "~",
  empty: "",
  colon_trail: "end:",
  multiline: "line one\nline two",
  spaced: " lead",
  null_value: null,
  true_value: true,
  count: 42,
  ratio: 0.5,
  negative: -7,
};

const GOLDEN_B = [
  'colon_trail: "end:"',
  "count: 42",
  'date_like: "2026-07-30"',
  'empty: ""',
  'float_like: "1.5e3"',
  'multiline: "line one\\nline two"',
  "negative: -7",
  "null_value: null",
  "plain: worker",
  "ratio: 0.5",
  'spaced: " lead"',
  'tilde: "~"',
  "true_value: true",
  'version_like: "007"',
  'yes_string: "yes"',
]
  .map((l) => `${l}\n`)
  .join("");

// ── Fixture C — nesting, sequences, empty collections, escapes ───────────────

const C_VALUE: Record<string, unknown> = {
  waves: [["p0", "p1"], ["p2"], []],
  team: {
    lead: { id: "p0", scope: null },
    tags: [],
    meta: {},
  },
  items: [
    { id: "a", deps: [] },
    { id: "b", deps: ["a"] },
  ],
  control: "tab\there",
  high: `${C1}del`,
};

const GOLDEN_C = [
  'control: "tab\\there"',
  'high: "\\x80del"',
  "items:",
  "  - deps: []",
  "    id: a",
  "  - deps:",
  "      - a",
  "    id: b",
  "team:",
  "  lead:",
  "    id: p0",
  "    scope: null",
  "  meta: {}",
  "  tags: []",
  "waves:",
  "  - - p0",
  "    - p1",
  "  - - p2",
  "  - []",
]
  .map((l) => `${l}\n`)
  .join("");

// ── Fixture D — the §1 self-referential hash over hand-authored bytes ────────

const D_CORE: Record<string, unknown> = {
  schema_version: "guild.demo.v1",
  payload: "x",
  demo_hash_algorithm: "sha256",
  demo_hash_scope: "canonical_yaml_with_demo_hash_field_omitted",
};

const GOLDEN_D_CORE = [
  "demo_hash_algorithm: sha256",
  "demo_hash_scope: canonical_yaml_with_demo_hash_field_omitted",
  "payload: x",
  "schema_version: guild.demo.v1",
]
  .map((l) => `${l}\n`)
  .join("");

describe("C12 team-contracts §1 — hand-authored golden bytes", () => {
  describe("golden fixtures pin BOTH implementations (runtime + independent reference)", () => {
    test.each([
      ["A (review probe doc)", A_VALUE, GOLDEN_A],
      ["B (scalar styles)", B_VALUE, GOLDEN_B],
      ["C (nesting/empties/escapes)", C_VALUE, GOLDEN_C],
      ["D core (hash input)", D_CORE, GOLDEN_D_CORE],
    ] as Array<[string, unknown, string]>)(
      "fixture %s: runtime serializer reproduces the hand-authored bytes",
      (_name, value, golden) => {
        expect(runtime.canonicalYaml(value)).toBe(golden);
      }
    );

    test.each([
      ["A (review probe doc)", A_VALUE, GOLDEN_A],
      ["B (scalar styles)", B_VALUE, GOLDEN_B],
      ["C (nesting/empties/escapes)", C_VALUE, GOLDEN_C],
      ["D core (hash input)", D_CORE, GOLDEN_D_CORE],
    ] as Array<[string, unknown, string]>)(
      "fixture %s: independent reference serializer reproduces the hand-authored bytes",
      (_name, value, golden) => {
        expect(referenceCanonicalYaml(value)).toBe(golden);
      }
    );

    test("empty-collection document forms", () => {
      expect(runtime.canonicalYaml({})).toBe("{}\n");
      expect(runtime.canonicalYaml([])).toBe("[]\n");
      expect(referenceCanonicalYaml({})).toBe("{}\n");
      expect(referenceCanonicalYaml([])).toBe("[]\n");
    });
  });

  describe("UTF-16-vs-codepoint probe (T2B-R1-F1 regression)", () => {
    test("U+E000 sorts BEFORE U+1F4A9 by code point, though UTF-16 code units say otherwise", () => {
      // Naive JS string comparison is UTF-16 code-unit order: the astral pair's
      // lead surrogate 0xD83D < 0xE000, i.e. the WRONG order under the frozen rule.
      expect(PUA < ASTRAL).toBe(false); // UTF-16 gets it backwards
      expect(runtime.codePointCompare(PUA, ASTRAL)).toBeLessThan(0);
      expect(runtime.codePointCompare(ASTRAL, PUA)).toBeGreaterThan(0);
      // Default Array.sort is UTF-16; codePointCompare corrects it:
      expect([ASTRAL, PUA].sort()).toEqual([ASTRAL, PUA]);
      expect([ASTRAL, PUA].sort(runtime.codePointCompare)).toEqual([PUA, ASTRAL]);
    });

    test("serialized key order in the probe document is code-point order (both impls)", () => {
      for (const out of [runtime.canonicalYaml(A_VALUE), referenceCanonicalYaml(A_VALUE)] as string[]) {
        const puaIdx = out.indexOf(PUA);
        const astralIdx = out.indexOf(ASTRAL);
        expect(puaIdx).toBeGreaterThanOrEqual(0);
        expect(astralIdx).toBeGreaterThanOrEqual(0);
        expect(puaIdx).toBeLessThan(astralIdx);
      }
    });

    test("[control] js-yaml sortKeys serialization does NOT reproduce the golden bytes (the round-1 defect)", () => {
      const jsYamlOut = yaml.dump(A_VALUE, { sortKeys: true });
      expect(jsYamlOut).not.toBe(GOLDEN_A);
    });
  });

  describe("quote-style probe (T2B-R1-F1 regression)", () => {
    test('the non-plain scalar "a # b" takes the DOUBLE-quoted fallback, never single quotes', () => {
      for (const out of [runtime.canonicalYaml(A_VALUE), referenceCanonicalYaml(A_VALUE)] as string[]) {
        expect(out).toContain('note: "a # b"');
        expect(out).not.toContain("'a # b'");
      }
      expect(runtime.doubleQuoted("a # b")).toBe('"a # b"');
    });

    test("[control] js-yaml's default fallback single-quotes the same scalar (the round-1 defect)", () => {
      expect(yaml.dump({ note: "a # b" })).toContain("'a # b'");
    });

    test("no single-quoted scalar appears in ANY golden fixture output", () => {
      for (const value of [A_VALUE, B_VALUE, C_VALUE, D_CORE]) {
        const out = runtime.canonicalYaml(value) as string;
        expect(out).not.toMatch(/: '/);
        expect(out).not.toMatch(/- '/);
      }
    });
  });

  describe("self-referential hash over hand-authored bytes (the frozen rule)", () => {
    test("runtime selfReferentialHash(artifact, field) = sha256(hand-authored core bytes)", () => {
      const expected = sha256(GOLDEN_D_CORE);
      const artifact = { ...D_CORE, demo_hash: "will-be-omitted-from-the-hash-input" };
      expect(runtime.selfReferentialHash(artifact, "demo_hash")).toBe(expected);
      expect(selfRefHash(artifact, "demo_hash")).toBe(expected);
      expect(runtime.sha256Hex(GOLDEN_D_CORE)).toBe(expected);
    });

    test("any byte change to the hashed value changes the hash (tamper detection)", () => {
      const expected = sha256(GOLDEN_D_CORE);
      const tampered = { ...D_CORE, payload: "y", demo_hash: "irrelevant" };
      expect(runtime.selfReferentialHash(tampered, "demo_hash")).not.toBe(expected);
    });
  });
});
