/**
 * Transitional re-export shim (T12 fold, KTD36).
 *
 * The implementation moved once into src/domains/evolve/. This file republishes the exact
 * pre-fold public surface of src/modules/evolution so existing importers keep working;
 * T16 deletes it. New code imports src/domains/evolve directly.
 */

export {
  AUTO_PATH_TARGETS,
  EVOLVE_DELTA_OPS,
  EVOLVE_DELTA_SCHEMA,
  EVOLVE_HISTORY_SCHEMA,
  EVOLVE_TARGETS,
  EvolveTargetRefusal,
  HUMAN_ONLY_TARGETS,
  LEARNING_CANDIDATE_SCHEMA,
  LEARNING_CANDIDATE_TYPES,
  applyEvolveDelta,
  assertAutoPathAllowed,
  assertCheapCurator,
  assertNotPermissionEdit,
  assertProjectHome,
  blockUnits,
  candidatePath,
  classifyAgentDef,
  classifyAgentTemplate,
  classifyAutoPath,
  classifyConfig,
  classifyDomainModel,
  classifyFileClass,
  classifyKnowledgeGraph,
  classifyMemory,
  classifyPermissionContent,
  classifyPhase,
  classifyReviewPolicy,
  classifySkillDef,
  classifySkillTemplate,
  classifyTaskTracking,
  classifyWiki,
  classifyWorkflowRules,
  compactHistoryPath,
  deriveLearningCandidates,
  evolveHome,
  findLatestOnlyViolation,
  isCuratorSpan,
  isEvolveTarget,
  isPermissionSentence,
  isValidLearningCandidate,
  lintReplacement,
  makeLearningCandidate,
  planEvolveDelta,
  projectTargetRoot,
  promotionGate,
  readCompactHistory,
  recommendedDestination,
  recordEvolveDelta,
  renderCuratorSpan,
  rollbackEvolve,
  routeCheckpointVerdict,
  sentences,
  sha256,
} from "../../domains/evolve";
export type {
  ArtifactSet,
  AutoPathVerdict,
  BlockUnit,
  CandidateScope,
  CheckpointRoute,
  Confidence,
  CuratorSpanInput,
  EvolveApplyContext,
  EvolveApplyResult,
  EvolveDelta,
  EvolveDeltaOp,
  EvolveDeltaPlan,
  EvolveHistory,
  EvolveHistoryEntry,
  EvolveHome,
  EvolveRefusalKind,
  EvolveTarget,
  FileClassVerdict,
  HandoffV2Block,
  HistoryOptions,
  Impact,
  LearningCandidate,
  LearningCandidateType,
  PermissionContentReason,
  PermissionContentVerdict,
  PhaseVerdict,
  PromotionGate,
  ProvenanceTouched,
  RecommendedDestination,
  RollbackResult,
  RollbackStatus,
  RollbackStep,
  Verdict,
} from "../../domains/evolve";
