/**
 * Transitional re-export shim (T12 fold, KTD36).
 *
 * The implementation moved once into src/domains/kernel/. This file republishes the exact
 * pre-fold public surface of src/modules/kernel so existing importers keep working;
 * T16 deletes it. New code imports src/domains/kernel directly.
 */

export {
  BUS_TIERS,
  CONTAINMENT_REFUSAL_CODES,
  LEAD_ROLE_IDS,
  MODULE_MANIFEST_SCHEMA_VERSION,
  OWNED_INVENTORY_CATEGORIES,
  PLUGIN_ROOT_MARKER,
  RUNTIME_SUBTREE_SEGMENTS,
  TIER_BUS_CONTRACT,
  TOKEN_RE,
  assertContained,
  assertNotRuntimeTree,
  authenticateBusTier,
  busAuthFailed,
  busRefused,
  busTierForRole,
  busTierForTopic,
  canonSegment,
  canonicalizeRealPath,
  checkBusMessage,
  checkBusPublish,
  checkContained,
  deepFreeze,
  findPluginRoot,
  formatBoundaryValidation,
  formatModuleHealthValidation,
  formatOwnershipValidation,
  freezeRegExpSafely,
  frozenList,
  isForbiddenRuntimeSubtree,
  isRefused,
  isSealedCollection,
  isWithin,
  loadModuleManifests,
  loadYamlApi,
  ownPluginRoot,
  ownersFor,
  prepareContainedWrite,
  regExpWritesLastIndex,
  resolvePluginRoot,
  sealMap,
  sealSet,
  sealedCollectionValues,
  splitCamel,
  tokenizeIdentifierAware,
  validateModuleBoundaries,
  validateModuleHealth,
  validateModuleOwnership,
  writeContainedFile,
} from "../../domains/kernel";
export type {
  BusAuthResult,
  BusDefect,
  BusIdentity,
  BusIdentityFacts,
  BusMessage,
  BusTier,
  BusVerdict,
  ContainedWriteResult,
  ContainmentOk,
  ContainmentOptions,
  ContainmentPolicy,
  ContainmentRefusalCode,
  ContainmentRefused,
  ContainmentResult,
  DeepFreezeOptions,
  ModuleBoundaryValidationResult,
  ModuleBoundaryViolation,
  ModuleHealthFinding,
  ModuleHealthFindingReason,
  ModuleHealthSummary,
  ModuleHealthValidationResult,
  ModuleImplementationMode,
  ModuleInventory,
  ModuleInventoryCategory,
  ModuleInventoryEntry,
  ModuleKind,
  ModuleManifest,
  ModuleOwns,
  ModuleValidationResult,
  OwnedInventoryCategory,
  OwnershipFinding,
  OwnershipValidationResult,
  PrepareResult,
  PreparedWrite,
  RegExpFreezePolicy,
  YamlApi,
} from "../../domains/kernel";
