/**
 * Transitional re-export shim (T12 fold, KTD36).
 *
 * The implementation moved once into src/domains/security/. This file republishes the exact
 * pre-fold public surface of src/modules/security so existing importers keep working;
 * T16 deletes it. New code imports src/domains/security directly.
 */

export {
  CANONICAL_RUN_LOG,
  FIELD_SIZE_CAP_BYTES,
  HIGH_ENTROPY_PATTERN,
  HIGH_ENTROPY_REDACTED,
  HOME_DIR_PATTERN,
  KNOWN_GUILD_HOST_KINDS,
  KV_REDACTED,
  KV_SECRET_PATTERN,
  MODULE_PUBLIC_API_VERSION,
  PATH_REDACTED,
  PROTO_POISON_KEYS,
  REDACTABLE_FIELDS,
  SECRET_PATTERNS,
  SECURITY_EVENT_SCHEMA_VERSION,
  SENSITIVE_HOME_DIRS,
  SHARED_SCRUBBED_NAMES,
  TOKEN_REDACTED,
  TOKEN_SHAPE_PATTERNS,
  TRUNCATION_SUFFIX,
  appendSecurityEvent,
  buildSecurityEvent,
  classifyEnvelope,
  emitRecallQuarantine,
  inShareSet,
  isCanonicalRunLog,
  isHandoffFile,
  isPayloadFile,
  isProtoPoisonKey,
  isRelativePathToken,
  isWhitelistedHighEntropy,
  redact,
  redactEventFields,
  redactField,
  redactHighEntropy,
  redactHomeDirPaths,
  redactKeyValueSecrets,
  redactShareableFile,
  redactTokenShapes,
  resolveHostResolution,
  resolveRunDir,
  sanitizeForInjection,
  scrubbedWrite,
  truncateToCap,
  writeScrubApprovalRequest,
  // T15: the D5 classifier and the closed security_event set moved/landed here.
  SECURITY_EVENT_TYPES,
  blockUnits,
  classifyPermissionContent,
  isPermissionSentence,
  sentences,
  INGEST_PAUSE_SCHEMA,
  clearIngestPause,
  ingestPauseBlocking,
  ingestPausePath,
  readIngestPause,
  recordIngestPause,
} from "../../domains/security";
export type {
  HostResolution,
  InjectionClean,
  RedactResult,
  SanitizeResult,
  ScrubSurface,
  ScrubbedWriteResult,
  SecretHit,
  SecurityDecision,
  SecurityEventInput,
  SecurityEventType,
  SecurityEventV1,
  BlockUnit,
  PermissionContentReason,
  PermissionContentVerdict,
  IngestPauseEntry,
  IngestPauseFile,
} from "../../domains/security";
