#!/usr/bin/env -S npx tsx
/**
 * hooks/maybe-reflect.ts
 *
 * Event:   Stop
 * Purpose: Fires guild:reflect ONLY if the §13.2 heuristic gate is satisfied.
 *
 * Heuristic gate (§13.2, §15.2):
 *   ✓  ≥ 1 specialist dispatched  → SubagentStop with non-empty specialist field
 *   ✓  ≥ 1 file edited            → PostToolUse with tool "Write" or "Edit"
 *   ✓  No error event             → all events have ok: true
 *
 * If gate fails → no-op (silent, exit 0). Prevents spurious reflections on
 * non-task sessions (§15.2 risk: "Stop hook fires on non-task sessions").
 *
 * If gate passes:
 *   1. Attempt to run scripts/trace-summarize.ts (tooling-engineer ships in P5 Task 3).
 *      If that script is missing, produce a compact stub summary from events.ndjson.
 *      Either way, write .guild/runs/<run-id>/summary.md.
 *   2. Emit one line to stdout telling the orchestrator to invoke guild:reflect:
 *        GUILD_REFLECT run_id=<run-id>
 *      The orchestrator reads this and invokes guild:reflect.
 *
 * Run-id resolution (priority order):
 *   1. GUILD_RUN_ID env var
 *   2. stdin payload session_id field
 *   3. fallback: "session-<date>"
 *
 * Working directory resolution (priority order):
 *   1. GUILD_CWD env var
 *   2. stdin payload cwd field
 *   3. process.cwd()
 *
 * Stdin:   JSON — Claude Code Stop hook payload.
 * Stdout:  Either empty (gate failed) or "GUILD_REFLECT run_id=<id>" (gate passed).
 * Stderr:  Diagnostic messages only.
 * Exit:    Always 0.
 *
 * Runner:  npx -y tsx hooks/maybe-reflect.ts
 */

import * as fs from "fs";
import * as path from "path";
import { spawnSync } from "child_process";

// ── Types ──────────────────────────────────────────────────────────────────

interface HookPayload {
  session_id?: string;
  cwd?: string;
  hook_event_name?: string;
  stop_reason?: string;
}

interface TelemetryEvent {
  ts: string;
  event: string;
  tool: string;
  specialist: string;
  payload_digest: string;
  ok: boolean;
  ms: number;
}

// ── Helpers ────────────────────────────────────────────────────────────────

/** Read all stdin into a string. */
async function readStdin(): Promise<string> {
  return new Promise((resolve) => {
    const chunks: Buffer[] = [];
    process.stdin.on("data", (c: Buffer) => chunks.push(c));
    process.stdin.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    process.stdin.on("error", () => resolve(""));
  });
}

/** Load and parse events.ndjson; returns empty array if missing or unparseable. */
function loadEvents(eventsFile: string): TelemetryEvent[] {
  if (!fs.existsSync(eventsFile)) return [];
  const content = fs.readFileSync(eventsFile, "utf8");
  const events: TelemetryEvent[] = [];
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      events.push(JSON.parse(trimmed) as TelemetryEvent);
    } catch {
      // skip malformed lines
    }
  }
  return events;
}

/**
 * Heuristic gate — all three conditions must hold:
 *   1. ≥ 1 specialist dispatched (SubagentStop with non-empty specialist)
 *   2. ≥ 1 file edited (PostToolUse with tool "Write" or "Edit")
 *   3. No error event (all ok: true)
 */
function gateCheck(events: TelemetryEvent[]): boolean {
  if (events.length === 0) return false;

  const hasSpecialist = events.some(
    (e) => e.event === "SubagentStop" && e.specialist && e.specialist.trim().length > 0
  );
  const hasFileEdit = events.some(
    (e) =>
      e.event === "PostToolUse" &&
      (e.tool === "Write" || e.tool === "Edit")
  );
  const hasError = events.some((e) => e.ok === false);

  return hasSpecialist && hasFileEdit && !hasError;
}

/**
 * Produce a compact stub summary from events and write it to summary.md.
 * Used when scripts/trace-summarize.ts is not yet available.
 */
function writeStubSummary(runDir: string, runId: string, events: TelemetryEvent[]): void {
  const specialists = [
    ...new Set(events.map((e) => e.specialist).filter(Boolean)),
  ];
  const tools = [...new Set(events.map((e) => e.tool).filter(Boolean))];
  const editCount = events.filter(
    (e) => e.tool === "Write" || e.tool === "Edit"
  ).length;
  const totalMs = events.reduce((acc, e) => acc + (e.ms ?? 0), 0);

  const lines = [
    `# Run summary: ${runId}`,
    "",
    `Generated: ${new Date().toISOString()} (stub — trace-summarize.ts not yet available)`,
    "",
    "## Specialists dispatched",
    specialists.length > 0 ? specialists.map((s) => `- ${s}`).join("\n") : "- (none)",
    "",
    "## Tool activity",
    `- Total events: ${events.length}`,
    `- File edits: ${editCount}`,
    `- Unique tools: ${tools.join(", ") || "(none)"}`,
    `- Total duration: ${totalMs}ms`,
    "",
    "## Outcome",
    "Gate passed: specialist dispatched, file edited, no errors.",
    "",
    "<!-- stub summary generated by maybe-reflect.ts; will be replaced by trace-summarize.ts -->",
  ];

  const summaryPath = path.join(runDir, "summary.md");
  fs.writeFileSync(summaryPath, lines.join("\n") + "\n", "utf8");
  process.stderr.write(`[maybe-reflect] wrote stub summary to ${summaryPath}\n`);
}

/**
 * Attempt to run scripts/trace-summarize.ts.
 * If it exists and succeeds, it writes summary.md itself.
 * Returns true if the real summarizer ran, false if it's missing (use stub).
 */
function tryRealSummarizer(cwd: string, runId: string): boolean {
  const summarizerPath = path.join(cwd, "scripts", "trace-summarize.ts");
  if (!fs.existsSync(summarizerPath)) return false;

  const result = spawnSync("npx", ["tsx", summarizerPath, runId], {
    cwd,
    encoding: "utf8",
    timeout: 15000,
    env: { ...process.env, GUILD_RUN_ID: runId },
  });

  if (result.status !== 0) {
    process.stderr.write(
      `[maybe-reflect] trace-summarize.ts exited ${result.status}: ${result.stderr ?? ""}\n`
    );
    return false;
  }
  return true;
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const raw = await readStdin();

  let payload: HookPayload = {};
  try {
    payload = JSON.parse(raw.trim()) as HookPayload;
  } catch {
    // Invalid JSON is fine — no-op silently
    process.stderr.write("[maybe-reflect] WARN: invalid JSON on stdin; treating as non-task stop.\n");
    process.exit(0);
  }

  // Resolve run context
  const cwd = process.env["GUILD_CWD"] ?? payload.cwd ?? process.cwd();
  const sessionId = payload.session_id ?? `session-${new Date().toISOString().slice(0, 10)}`;
  const runId = process.env["GUILD_RUN_ID"] ?? sessionId;

  // Load telemetry events
  const eventsFile = path.join(cwd, ".guild", "runs", runId, "events.ndjson");
  const events = loadEvents(eventsFile);

  // Heuristic gate check
  if (!gateCheck(events)) {
    // Gate failed — no-op, no stdout, exit 0
    process.stderr.write(
      `[maybe-reflect] gate failed for run ${runId} — skipping reflection.\n`
    );
    process.exit(0);
  }

  // Gate passed — produce summary, then tell orchestrator to reflect
  const runDir = path.join(cwd, ".guild", "runs", runId);

  const usedRealSummarizer = tryRealSummarizer(cwd, runId);
  if (!usedRealSummarizer) {
    writeStubSummary(runDir, runId, events);
  }

  // Emit reflect marker to stdout — orchestrator reads this line
  process.stdout.write(`GUILD_REFLECT run_id=${runId}\n`);
  process.exit(0);
}

main().catch((err: unknown) => {
  process.stderr.write(
    `[maybe-reflect] FATAL: ${err instanceof Error ? err.message : String(err)}\n`
  );
  process.exit(0); // Always exit 0
});
