/**
 * scripts/dot-guild/convert/convert.ts — applies the §2 26-row mapping table.
 *
 * Operates ONLY after a verified snapshot (the caller guarantees this). For each
 * v1 source it partitions keys per §2.0a (C1/C2/C3/C4), writes the v2 artifact,
 * relocates C2 keys to `.unmigrated-v1.json`, and removes the live v1 source IFF
 * every key is C1/C2/C3 (zero C4) — the §2.0a removal predicate. Strict ordering
 * (§2.0): snapshot (done) → write v2 → write .unmigrated-v1.json → re-verify →
 * THEN remove live source. A C4 conflict (or unreconstructable source) keeps the
 * source LIVE (preserve+flag) and is re-surfaced.
 *
 * dryRun=true: compute every record + would-relocate + would-remove, write NOTHING.
 */

import * as path from "path";
import type {
  Fs,
  Clock,
  ArtifactRecord,
  KeyOutcome,
  UnmigratedEntry,
} from "./types";
import { parseJson, parseYaml } from "./seams";
import { v1KeysIn } from "./detect";
import {
  classifyKey,
  setPath,
  buildUnmigratedDoc,
  valueEqual,
  getPath,
  mapV1Key,
} from "./keymap";

export interface ConvertOutput {
  artifacts: ArtifactRecord[];
  relocated: UnmigratedEntry[];
  conflicts: KeyOutcome[];
  /** Paths (rel to .guild) removed from the live tree (v1 sources). */
  removed: string[];
  /**
   * Paths (rel to .guild) that were GENERATED by this migration run (new v2
   * artifacts absent from the snapshot). These must be listed in the restore
   * command so a `rm -f <generated> && cp -R snapshot/. .guild/` round-trip
   * leaves the tree byte-identical to pre-migration. (P1 fix.)
   */
  generated: string[];
}

interface Ctx {
  fs: Fs;
  clock: Clock;
  guildDir: string;
  dryRun: boolean;
  snapshotRef: string;
  out: ConvertOutput;
  /** Accumulated relocations across all sources (one shared .unmigrated-v1.json). */
}

function rel(guildDir: string, p: string): string {
  return path.relative(guildDir, p);
}

/** Read the existing v2 settings.json (object) if present + parseable. */
function readSettings(fs: Fs, p: string): Record<string, unknown> {
  if (!fs.existsSync(p)) return {};
  const res = parseJson(fs.readFileSync(p));
  return res.ok && res.value && typeof res.value === "object"
    ? (res.value as Record<string, unknown>)
    : {};
}

/** Read a possibly-dotted key value out of a parsed config object. */
function readKeyValue(parsed: Record<string, unknown>, dotted: string): unknown {
  if (dotted in parsed) return parsed[dotted];
  return getPath(parsed, dotted);
}

/**
 * Remove a v1 key (possibly dotted) from a config object.
 *
 * Handles two representations of a dotted key (P2 literal-dotted-key fix):
 *   1. Literal top-level key: `{ "wiki.share_mode": "private" }` — YAML that
 *      was written with a literal dot in the key name (not nested). Removed via
 *      `delete obj[dotted]` first.
 *   2. Nested path: `{ wiki: { share_mode: "private" } }` — the more typical
 *      YAML nesting. Removed by descending the split path.
 * Both may co-exist (unusual but possible), so both are always attempted.
 */
function stripKey(obj: Record<string, unknown>, dotted: string): void {
  // (1) Literal top-level dotted key (e.g. "wiki.share_mode" stored verbatim).
  if (dotted in obj) delete obj[dotted];

  // (2) Nested path (the canonical nested representation).
  const parts = dotted.split(".");
  if (parts.length === 1) return; // already handled above
  let cur: unknown = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (cur && typeof cur === "object" && parts[i] in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[parts[i]];
    } else {
      return;
    }
  }
  if (cur && typeof cur === "object") delete (cur as Record<string, unknown>)[parts[parts.length - 1]];
}

/**
 * Main convert entry — iterates the §2 rows that produce action. carry-forward
 * rows are not visited (they need no work); the report records them separately if
 * desired, but the converter touches only convert/preserve+flag artifacts.
 */
export function convert(
  fs: Fs,
  clock: Clock,
  guildDir: string,
  dryRun: boolean,
  snapshotRef: string
): ConvertOutput {
  const out: ConvertOutput = { artifacts: [], relocated: [], conflicts: [], removed: [], generated: [] };
  const ctx: Ctx = { fs, clock, guildDir, dryRun, snapshotRef, out };
  const j = (r: string) => path.join(guildDir, r);
  // Deferred removals (P2 delete-before-write fix): v1 source files are collected
  // here and only deleted AFTER all v2 artifacts have been written. If any write
  // throws mid-pipeline, sources are never removed without a completed replacement.
  const deferredRemovals: string[] = [];

  const settingsPath = j("settings.json");
  const v2Settings = readSettings(fs, settingsPath);
  let settingsMutated = false;

  // ── NORMALIZE v2 surfaces FIRST (P2 normalize-before-cross-file fix) ──────
  // settings.json and settings.local.json may carry stray v1 aliases
  // (e.g. auto_approve: "spec-and-plan"). If we process config.yml first, the
  // cross-file conflict check compares config.yml's value against the RAW v1
  // alias string in v2Settings → false C4. By normalising v2Settings in-place
  // first, the conflict check sees the authoritative v2 array form → correct
  // C3/C4 result.

  // ── Row: settings.json carrying a stray v1 key (hand-mixed) ───────────────
  convertV2SurfaceInPlace(ctx, settingsPath, v2Settings, (mut) => {
    if (mut) settingsMutated = true;
  });

  // ── Row: settings.local.json carrying a v1 key (P9 / CF-W1b-7) ────────────
  convertSettingsLocal(ctx, j, guildDir, out);

  // ── Row: config.yml → settings.json (+ .unmigrated-v1.json) ───────────────
  {
    const p = j("config.yml");
    if (fs.existsSync(p)) {
      const res = parseYaml(fs.readFileSync(p));
      if (!res.ok || !res.value || typeof res.value !== "object") {
        // Should not happen (corrupt would have blocked), but be safe: preserve+flag.
        out.artifacts.push({
          rel: rel(guildDir, p),
          disposition: "preserve+flag",
          note: "config.yml unparseable at convert time — preserved",
        });
      } else {
        const parsed = res.value as Record<string, unknown>;
        const v1Keys = v1KeysIn(parsed);
        // config.yml may also carry mappable-but-not-"v1-only" keys (loops/loop_cap/
        // codex_cap) — those are C1 carry-into-settings if absent in v2.
        const carryKeys = ["loops", "loop_cap", "codex_cap"].filter((k) => k in parsed);
        const allKeys = [...new Set([...v1Keys, ...carryKeys])];
        const { outcomes, mutated } = convertSurfaceWithCarry(
          ctx,
          rel(guildDir, p),
          parsed,
          v2Settings,
          allKeys
        );
        if (mutated) settingsMutated = true;
        // Any remaining key in config.yml with no v2 home + not handled ⇒ C2 relocate.
        //
        // PARTIAL-PARENT handling (P1 regression fix): when a top-level key `k` is a
        // CONTAINER object whose sub-paths were PARTIALLY handled (some in `allKeys`,
        // some not), we must NOT skip the entire container (that loses unhandled
        // siblings like `defaults.auto_learn`) AND we must NOT relocate the whole
        // container (that duplicates already-migrated data). Instead:
        //   1. If `k` itself is in allKeys → it was directly handled; skip.
        //   2. If `k` has NO descendant in allKeys → fully unhandled; classify+relocate as-is.
        //   3. If `k` has SOME handled descendants → partial parent: strip the handled
        //      sub-keys from a deep-clone, then relocate only the remainder. If the
        //      remainder is empty (all descendants were handled), skip (nothing to relocate).
        for (const k of Object.keys(parsed)) {
          if (allKeys.includes(k)) continue;
          const handledChildren = allKeys.filter((hk) => hk.startsWith(k + "."));
          if (handledChildren.length === 0) {
            // Fully unhandled top-level key — classify AND APPLY.
            // Includes literal dotted keys like "defaults.agent_team" that v1KeysIn
            // does not put in allKeys (because v1KeysIn reads nested paths, not literal
            // dotted-string keys). classifyKey may return C1 (write to v2) for these —
            // we MUST apply the write here, not just record it. (P1 data-loss fix.)
            const cls = classifyKey(k, parsed[k], v2Settings);
            outcomes.push(cls.outcome);
            if (cls.write) {
              // C1: apply the v2 value into settings and mark settings as mutated.
              setPath(v2Settings, cls.write.v2Key, cls.write.v2Value);
              settingsMutated = true;
            }
            if (cls.relocate)
              out.relocated.push({ source: rel(guildDir, p), key: k, value: parsed[k], reason: "unmapped" });
            if (cls.outcome.case === "C4") out.conflicts.push(cls.outcome);
          } else {
            // Partial parent: remove handled sub-keys from a clone, then relocate the rest.
            const remainder = stripHandledLeaves(parsed[k], k, allKeys);
            if (remainder !== undefined) {
              // There are unhandled leaves/subtrees — relocate only those.
              out.relocated.push({ source: rel(guildDir, p), key: k, value: remainder, reason: "unmapped" });
              outcomes.push({ key: k, case: "C2", detail: `partial parent: unhandled sub-keys relocated (handled: ${handledChildren.join(", ")})` });
            }
            // else: all descendants were handled → nothing to relocate; skip.
          }
        }
        const anyC4 = outcomes.some((o) => o.case === "C4");
        const sourceRemovable = !anyC4;
        out.artifacts.push({
          rel: rel(guildDir, p),
          disposition: anyC4 ? "preserve+flag" : "convert",
          target: "settings.json",
          keys: outcomes,
          note: anyC4
            ? "C4 conflict — config.yml kept LIVE, tree stays mixed, re-surface next open"
            : "converted to settings.json; removed from live (snapshot holds original)",
          removed: sourceRemovable,
        });
        // Defer removal until AFTER all v2 writes complete (P2 delete-before-write fix).
        if (sourceRemovable) {
          if (!dryRun) deferredRemovals.push(p);
          out.removed.push(rel(guildDir, p));
        }
      }
    }
  }

  // ── Row: project.yaml wiki.share_mode → settings.json defaults.wiki.share_mode
  {
    const p = j("project.yaml");
    if (fs.existsSync(p)) {
      const res = parseYaml(fs.readFileSync(p));
      if (res.ok && res.value && typeof res.value === "object") {
        const parsed = res.value as Record<string, unknown>;
        const shareVal = readKeyValue(parsed, "wiki.share_mode");
        if (shareVal !== undefined) {
          const cls = classifyKey("wiki.share_mode", shareVal, v2Settings);
          const outcomes = [cls.outcome];
          if (cls.write) {
            setPath(v2Settings, cls.write.v2Key, cls.write.v2Value);
            settingsMutated = true;
          }
          const isC4 = cls.outcome.case === "C4";
          if (isC4) out.conflicts.push(cls.outcome);
          // project.yaml is identity-bearing — NEVER removed; only the migrated key
          // is stripped (C1/C3). On C4 the key stays LIVE.
          if (!isC4 && !dryRun) {
            stripKey(parsed, "wiki.share_mode");
            fs.writeFileSync(p, serializeYaml(parsed));
          }
          out.artifacts.push({
            rel: rel(guildDir, p),
            disposition: isC4 ? "preserve+flag" : "convert",
            target: "settings.json:defaults.wiki.share_mode",
            keys: outcomes,
            note: isC4
              ? "C4 share_mode conflict — wiki.share_mode kept LIVE in project.yaml, settings.json NOT clobbered, re-surface"
              : cls.outcome.case === "C3"
                ? "redundant share_mode dropped from project.yaml (settings.json authoritative)"
                : "wiki.share_mode moved to settings.json; key removed from project.yaml",
            removed: false,
          });
        }
      }
    }
  }

  // ── Row: runs/<id>/metadata.json (no run.yaml) → run.yaml + provenance.json
  convertLegacyRuns(ctx);

  // ── Persist settings.json once (single write) ─────────────────────────────
  if (settingsMutated && !dryRun) {
    const settingsIsNew = !fs.existsSync(settingsPath);
    fs.writeFileSync(settingsPath, JSON.stringify(v2Settings, null, 2) + "\n");
    // Track as generated only if it didn't exist before this migration run
    // (otherwise the snapshot already holds it and the restore overwrites it).
    if (settingsIsNew) out.generated.push(rel(guildDir, settingsPath));
  }

  // ── Write the shared .unmigrated-v1.json ─────────────────────────────────
  // Merge with any EXISTING .unmigrated-v1.json from a prior partial migration
  // (never clobber). Deduplicate by (source, key) so a repeated run with an
  // unresolved C4+C2 source does not accumulate duplicate entries. (P3 fix.)
  if (out.relocated.length > 0 && !dryRun) {
    const unmigratedPath = j(".unmigrated-v1.json");
    const isNew = !fs.existsSync(unmigratedPath);
    let mergedEntries: UnmigratedEntry[] = [];
    if (!isNew) {
      const existing = parseJson(fs.readFileSync(unmigratedPath));
      if (existing.ok && existing.value && typeof existing.value === "object") {
        const prior = (existing.value as Record<string, unknown>)["entries"];
        if (Array.isArray(prior)) mergedEntries = prior as UnmigratedEntry[];
      }
    }
    // UPSERT by (source, key): if the identity already exists in the prior entries,
    // REPLACE its value with the current run's (newer) value — the user may have
    // edited the source between runs while a C4 kept it live. If the identity is
    // new, append it. This gives no-duplicate AND latest-value-wins semantics. (P2b fix.)
    const indexMap = new Map(mergedEntries.map((e, i) => [`${e.source}\0${e.key}`, i]));
    for (const entry of out.relocated) {
      const id = `${entry.source}\0${entry.key}`;
      const existing = indexMap.get(id);
      if (existing !== undefined) {
        // Replace with current run's entry (newer value wins).
        mergedEntries[existing] = entry;
      } else {
        indexMap.set(id, mergedEntries.length);
        mergedEntries.push(entry);
      }
    }
    const doc = buildUnmigratedDoc(clock.iso(), snapshotRef, mergedEntries);
    fs.writeFileSync(unmigratedPath, doc);
    if (isNew) out.generated.push(rel(guildDir, unmigratedPath));
  }

  // ── Drain deferred removals (P2 delete-before-write fix) ─────────────────
  // All v2 artifacts are now durably written above. Only NOW remove the live
  // v1 sources. If any write above had thrown, we would never reach here and
  // the sources would survive intact (snapshot already holds the backup).
  for (const p of deferredRemovals) {
    fs.rmFileSync(p);
  }

  return out;
}

/**
 * Convert a config surface that mixes v1-only keys AND carry-keys (loops/loop_cap/
 * codex_cap). carry-keys are C1 into settings.json when absent, C3 when equal,
 * C4 when differing.
 */
function convertSurfaceWithCarry(
  ctx: Ctx,
  sourceRel: string,
  parsed: Record<string, unknown>,
  v2Target: Record<string, unknown>,
  keys: string[]
): { outcomes: KeyOutcome[]; mutated: boolean } {
  const outcomes: KeyOutcome[] = [];
  let mutated = false;
  for (const k of keys) {
    const value = readKeyValue(parsed, k);
    // carry-keys (loops/loop_cap/codex_cap) map to the SAME key name in v2.
    if (k === "loops" || k === "loop_cap" || k === "codex_cap") {
      const existing = getPath(v2Target, k);
      if (existing === undefined) {
        setPath(v2Target, k, normalizeCarry(k, value));
        mutated = true;
        outcomes.push({ key: k, case: "C1", detail: `${k}=${JSON.stringify(normalizeCarry(k, value))}` });
      } else if (valueEqual(existing, normalizeCarry(k, value))) {
        outcomes.push({ key: k, case: "C3", detail: `${k} redundant (already ${JSON.stringify(existing)})` });
      } else {
        outcomes.push({ key: k, case: "C4", detail: `${k} conflict: v2=${JSON.stringify(existing)} vs v1=${JSON.stringify(value)}` });
        ctx.out.conflicts.push(outcomes[outcomes.length - 1]);
      }
      continue;
    }
    const cls = classifyKey(k, value, v2Target);
    outcomes.push(cls.outcome);
    if (cls.write) {
      setPath(v2Target, cls.write.v2Key, cls.write.v2Value);
      mutated = true;
    }
    if (cls.relocate)
      ctx.out.relocated.push({ source: sourceRel, key: cls.relocate.key, value: cls.relocate.value, reason: "unmapped" });
    if (cls.outcome.case === "C4") {
      ctx.out.conflicts.push(cls.outcome);
    }
  }
  return { outcomes, mutated };
}

function normalizeCarry(k: string, v: unknown): unknown {
  if (k === "loop_cap" && typeof v === "number") return Math.min(256, Math.max(1, v));
  if (k === "codex_cap" && typeof v === "number") return Math.min(10, Math.max(1, v));
  return v;
}

/**
 * Process settings.local.json carrying v1 keys — extracted to a named function
 * so it can be called BEFORE config.yml processing (normalize-before-cross-file
 * ordering). settings.local.json is an IN-PLACE v2 override surface; same-name
 * aliases transform in-place (inPlace=true).
 */
function convertSettingsLocal(
  ctx: Ctx,
  j: (r: string) => string,
  guildDir: string,
  out: ConvertOutput
): void {
  const { fs, dryRun } = ctx;
  const p = j("settings.local.json");
  if (!fs.existsSync(p)) return;
  const res = parseJson(fs.readFileSync(p));
  if (!res.ok || !res.value || typeof res.value !== "object") return;
  const parsed = res.value as Record<string, unknown>;
  const v1Keys = v1KeysIn(parsed);
  if (v1Keys.length === 0) return;
  const outcomes: KeyOutcome[] = [];
  let anyC4 = false;
  let localMutated = false;
  for (const k of v1Keys) {
    const value = readKeyValue(parsed, k);
    // settings.local.json is a v2-era IN-PLACE override surface that is
    // deep-merged OVER settings.json at load time. Its v1 aliases must migrate
    // within the local file itself — not conflict against settings.json.
    //
    // - Same-name aliases (auto_approve string→array): inPlace=true bypasses the
    //   target lookup entirely, always C1/C3. Correct — the alias transforms in place.
    // - Different-name aliases (codex_review→review, defaults.agent_team→agent_mode):
    //   inPlace=true doesn't help (the same-name gate is `v1Key===v2Key && inPlace`).
    //   We pass `parsed` as the v2Target so the lookup checks whether the LOCAL file
    //   already has the v2 key — not settings.json. If the local file already has
    //   `review: "local"` AND `codex_review: true`, those differ → genuine C4 within
    //   the local surface. If the local file has no `review` key at all, the alias
    //   maps to a new `review: "cross"` written INTO settings.local.json. This keeps
    //   the override intent intact (the user wanted a local override, so we migrate
    //   it as a local override).
    const cls = classifyKey(k, value, parsed, /*inPlace=*/true);
    outcomes.push(cls.outcome);
    if (cls.write) {
      setPath(parsed, cls.write.v2Key, cls.write.v2Value);
      if (cls.write.v1Key !== cls.write.v2Key) stripKey(parsed, k);
      localMutated = true;
    } else if (cls.relocate) {
      out.relocated.push({ source: rel(guildDir, p), key: k, value, reason: "unmapped" });
      stripKey(parsed, k);
      localMutated = true;
    } else if (cls.outcome.case === "C3") {
      stripKey(parsed, k);
      localMutated = true;
    } else if (cls.outcome.case === "C4") {
      anyC4 = true;
      out.conflicts.push(cls.outcome);
    }
  }
  if (localMutated && !dryRun) fs.writeFileSync(p, JSON.stringify(parsed, null, 2) + "\n");
  out.artifacts.push({
    rel: rel(guildDir, p),
    disposition: anyC4 ? "preserve+flag" : "convert",
    keys: outcomes,
    note: anyC4
      ? "C4 conflict — deprecated alias kept LIVE in settings.local.json, re-surface"
      : "v1 keys migrated in place (file is a v2 surface; stays)",
    removed: false,
  });
}

/**
 * A v2 surface file (settings.json / settings.local.json) that carries a stray v1
 * key: rewrite in place to v2 form (C1), drop redundant (C3), relocate unmapped
 * (C2), keep C4 live.
 *
 * SAME-NAME ALIAS handling (P2 fix — auto_approve string→array):
 * When v1Key === v2Key (the transform keeps the same key name but changes the VALUE
 * shape, e.g. auto_approve "spec-and-plan" → ["spec","plan"]), the "existing" v2
 * value IS the v1 value — there is no separate v2 counterpart to conflict with. In
 * this case we always do an in-place replace (C1: write the transformed v2 value in
 * place, do NOT strip the key afterward since stripping would delete what we just
 * wrote). We never compare a same-name alias against itself for a C4 — a C4 can
 * only arise when v1Key !== v2Key and a DIFFERENT key already holds a v2 value.
 */
function convertV2SurfaceInPlace(
  ctx: Ctx,
  p: string,
  v2Obj: Record<string, unknown>,
  onMutate: (mutated: boolean) => void
): void {
  if (!ctx.fs.existsSync(p)) return;
  const v1Keys = v1KeysIn(v2Obj);
  if (v1Keys.length === 0) return;
  const outcomes: KeyOutcome[] = [];
  let anyC4 = false;
  let mutated = false;
  for (const k of v1Keys) {
    const value = readKeyValue(v2Obj, k);
    const mapped = mapV1Key(k, value);
    if (!mapped) {
      ctx.out.relocated.push({ source: rel(ctx.guildDir, p), key: k, value, reason: "unmapped" });
      stripKey(v2Obj, k);
      mutated = true;
      outcomes.push({ key: k, case: "C2", detail: `relocated verbatim (${JSON.stringify(value)})` });
      continue;
    }
    // Same-name alias (v1Key === v2Key): the current value IS the v1 form —
    // no separate counterpart exists. Always C1 (transform in place); never C4.
    if (mapped.v1Key === mapped.v2Key) {
      // The value is already the transformed form iff valueEqual (C3), else C1.
      if (valueEqual(value, mapped.v2Value)) {
        // C3: value is already in the correct v2 shape — nothing to do.
        outcomes.push({ key: k, case: "C3", detail: `${k} already in v2 form ${JSON.stringify(value)}` });
      } else {
        // C1: replace in place (do NOT strip — v1Key === v2Key; stripping drops the value).
        setPath(v2Obj, mapped.v2Key, mapped.v2Value);
        mutated = true;
        outcomes.push({ key: k, case: "C1", detail: `${k} transformed in-place → ${JSON.stringify(mapped.v2Value)}` });
      }
      continue;
    }
    // Different-name mapping: check for a pre-existing v2 counterpart.
    const existing = getPath(v2Obj, mapped.v2Key);
    if (existing === undefined) {
      setPath(v2Obj, mapped.v2Key, mapped.v2Value);
      stripKey(v2Obj, k);
      mutated = true;
      outcomes.push({ key: k, case: "C1", detail: `${k} → ${mapped.v2Key}=${JSON.stringify(mapped.v2Value)}` });
    } else if (valueEqual(existing, mapped.v2Value)) {
      stripKey(v2Obj, k);
      mutated = true;
      outcomes.push({ key: k, case: "C3", detail: `redundant: ${mapped.v2Key} already ${JSON.stringify(existing)}` });
    } else {
      anyC4 = true;
      outcomes.push({
        key: k,
        case: "C4",
        detail: `CONFLICT: ${mapped.v2Key}=${JSON.stringify(existing)} vs v1 ${k}=${JSON.stringify(value)} → kept LIVE`,
      });
      ctx.out.conflicts.push(outcomes[outcomes.length - 1]);
    }
  }
  onMutate(mutated);
  ctx.out.artifacts.push({
    rel: rel(ctx.guildDir, p),
    disposition: anyC4 ? "preserve+flag" : "convert",
    keys: outcomes,
    note: anyC4
      ? "C4 stray-key conflict — v1 key kept LIVE in settings.json, re-surface"
      : "stray v1 key(s) rewritten in place to v2 form",
    removed: false,
  });
}

/**
 * runs/<id>/metadata.json (no sibling run.yaml) → reconstruct run.yaml +
 * provenance.json. If fields are insufficient → preserve+flag (CF-W1b-4: do NOT
 * fabricate). events.ndjson is carry-forward (CF-W1b-3).
 */
function convertLegacyRuns(ctx: Ctx): void {
  const { fs, guildDir, dryRun } = ctx;
  const runsDir = path.join(guildDir, "runs");
  if (!fs.existsSync(runsDir)) return;
  let entries;
  try {
    entries = fs.readdirSync(runsDir);
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isDirectory) continue;
    const runDir = path.join(runsDir, e.name);
    const meta = path.join(runDir, "metadata.json");
    const runYaml = path.join(runDir, "run.yaml");
    if (!fs.existsSync(meta) || fs.existsSync(runYaml)) continue;
    const res = parseJson(fs.readFileSync(meta));
    if (!res.ok || !res.value || typeof res.value !== "object") {
      ctx.out.artifacts.push({
        rel: rel(guildDir, meta),
        disposition: "preserve+flag",
        note: "metadata.json unparseable — preserved",
        removed: false,
      });
      continue;
    }
    const m = res.value as Record<string, unknown>;
    const runId = (m["run_id"] ?? m["id"] ?? e.name) as string;
    // Prefer `started_at`; fall back to `created_at` for legacy metadata that
    // only carried `created_at`. The canonical guild.run.v1 field is `started_at`.
    const startedAt = (m["started_at"] ?? m["created_at"]) as string | undefined;
    // Minimal faithfulness check (CF-W1b-4): need at least a run id + a timestamp.
    if (!runId || !startedAt) {
      ctx.out.artifacts.push({
        rel: rel(guildDir, meta),
        disposition: "preserve+flag",
        note: "insufficient fields to reconstruct a faithful run.yaml — preserved (NOT fabricated)",
        removed: false,
      });
      continue;
    }
    // initiative_attachment is the canonical guild.run.v1 field name (not "initiative").
    // Accept either form from legacy metadata.json.
    const initiativeAttachment = (m["initiative_attachment"] ?? m["initiative"] ?? null) as string | null;

    const provPath = path.join(runDir, "provenance.json");
    const provExists = fs.existsSync(provPath);

    // Derive ONE fallback status used for BOTH run.yaml and provenance.json so
    // they stay consistent. Legacy metadata runs are historical (the process is
    // gone), so "closed" is the honest default. (P2 status-mismatch fix.)
    const runStatus = (m["status"] as string | undefined) ?? "closed";

    // Emit canonical guild.run.v1 field names per the run-lifecycle-contract.md
    // field table: started_at (not created_at), initiative_attachment (not initiative).
    const runDoc =
      `schema_version: guild.run.v1\n` +
      `run_id: ${runId}\n` +
      `started_at: ${startedAt}\n` +
      (initiativeAttachment ? `initiative_attachment: ${initiativeAttachment}\n` : `initiative_attachment: null\n`) +
      `status: ${runStatus}\n`;

    // Run-level C4 analog: if provenance.json already exists (an existing v2
    // artifact), this is a genuine conflict — keep metadata.json LIVE (never write
    // run.yaml, never delete metadata.json) and re-surface next open. Writing
    // run.yaml + deleting metadata.json while provenance.json exists would silently
    // "resolve" the conflict without user action, leaving the tree with a fabricated
    // run.yaml and no way to re-surface. (P2 fix — round-2 correction.)
    if (provExists) {
      ctx.out.artifacts.push({
        rel: rel(guildDir, meta),
        disposition: "preserve+flag",
        note: `run-level conflict: provenance.json already exists — metadata.json kept LIVE, run.yaml NOT written, re-surface next open`,
        removed: false,
      });
      // Nothing written, nothing removed. Source stays live; detection re-fires P6
      // on the next open so the conflict re-surfaces correctly.
      continue;
    }

    // provenance.json canonical fields per run-lifecycle-contract.md §2:
    //   initiative mirrors run.yaml.initiative_attachment (the provenance field is "initiative")
    //   started_at mirrors run.yaml.started_at
    //   status uses the same derived runStatus for consistency with run.yaml.
    const provDoc = {
      schema_version: "guild.provenance.v1",
      run_id: runId,
      initiative: initiativeAttachment,
      started_at: startedAt,
      reconstructed_from: "metadata.json",
      status: runStatus,
    };
    if (!dryRun) {
      fs.writeFileSync(runYaml, runDoc);
      fs.writeFileSync(provPath, JSON.stringify(provDoc, null, 2) + "\n");
      ctx.out.generated.push(rel(guildDir, runYaml));
      ctx.out.generated.push(rel(guildDir, provPath));
      fs.rmFileSync(meta);
    }
    ctx.out.removed.push(rel(guildDir, meta));
    ctx.out.artifacts.push({
      rel: rel(guildDir, meta),
      disposition: "convert",
      target: `runs/${e.name}/run.yaml + provenance.json`,
      note: "legacy metadata.json → run.yaml/provenance reconstructed; metadata.json moved to snapshot",
      removed: true,
    });
  }
}

/**
 * Minimal YAML serializer for the flat project.yaml shape we re-write (after
 * stripping wiki.share_mode). Uses js-yaml via seams to stay lossless for the
 * shapes we touch.
 */
/**
 * Given a container value `obj` (whose dotted path is `prefix`) and the set of
 * fully-handled dotted key paths `handledKeys`, return a deep clone of `obj`
 * with all handled leaf paths removed. Returns `undefined` if the resulting
 * object is empty (every descendant was handled). Returns `obj` as-is if it is
 * not a plain object (non-object unhandled value — caller relocates it whole).
 *
 * Example: prefix="defaults", obj={agent_team:"on", auto_learn:false},
 *   handledKeys=["defaults.agent_team"]
 *   → returns {auto_learn:false}  (agent_team stripped, auto_learn kept)
 */
function stripHandledLeaves(
  obj: unknown,
  prefix: string,
  handledKeys: string[]
): unknown {
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) {
    // Not a plain object — unhandled as-is (can't strip sub-keys from a scalar/array).
    return obj;
  }
  const rec = obj as Record<string, unknown>;
  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(rec)) {
    const dotted = `${prefix}.${k}`;
    if (handledKeys.includes(dotted)) continue; // this exact leaf was handled
    // Check if this sub-key has its own handled descendants (recurse).
    const handledBelow = handledKeys.filter((hk) => hk.startsWith(dotted + "."));
    if (handledBelow.length > 0) {
      // Partially-handled sub-container: recurse.
      const sub = stripHandledLeaves(v, dotted, handledKeys);
      if (sub !== undefined) result[k] = sub;
      // else all sub-children handled → k contributes nothing
    } else {
      // Fully unhandled leaf or sub-container — keep it.
      result[k] = v;
    }
  }
  return Object.keys(result).length === 0 ? undefined : result;
}

function serializeYaml(obj: Record<string, unknown>): string {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const yaml = require("js-yaml") as { dump(o: unknown): string };
  return yaml.dump(obj);
}
