/**
 * scripts/dot-guild/convert/convert.ts — applies the §2 26-row mapping table.
 *
 * Operates ONLY after a verified snapshot (the caller guarantees this). For each
 * v1 source it partitions keys per §2.0a (C1/C2/C3/C4), writes the v2 artifact,
 * relocates C2 keys to `.unmigrated-v1.json`, and removes the live v1 source IFF
 * every key is C1/C2/C3 (zero C4) — the §2.0a removal predicate. Strict ordering
 * (§2.0): snapshot (done) → write v2 → write .unmigrated-v1.json → re-verify →
 * THEN remove live source. A C4 conflict (or unreconstructable source) keeps the
 * source LIVE (preserve+flag) and is re-surfaced.
 *
 * dryRun=true: compute every record + would-relocate + would-remove, write NOTHING.
 */

import * as path from "path";
import type {
  Fs,
  Clock,
  ArtifactRecord,
  KeyOutcome,
  UnmigratedEntry,
} from "./types";
import { parseJson, parseYaml } from "./seams";
import { v1KeysIn } from "./detect";
import {
  classifyKey,
  setPath,
  buildUnmigratedDoc,
  valueEqual,
  getPath,
  mapV1Key,
} from "./keymap";

export interface ConvertOutput {
  artifacts: ArtifactRecord[];
  relocated: UnmigratedEntry[];
  conflicts: KeyOutcome[];
  /** Paths (rel to .guild) removed from the live tree (v1 sources). */
  removed: string[];
  /**
   * Paths (rel to .guild) that were GENERATED by this migration run (new v2
   * artifacts absent from the snapshot). These must be listed in the restore
   * command so a `rm -f <generated> && cp -R snapshot/. .guild/` round-trip
   * leaves the tree byte-identical to pre-migration. (P1 fix.)
   */
  generated: string[];
}

interface Ctx {
  fs: Fs;
  clock: Clock;
  guildDir: string;
  dryRun: boolean;
  snapshotRef: string;
  out: ConvertOutput;
  /** Accumulated relocations across all sources (one shared .unmigrated-v1.json). */
}

function rel(guildDir: string, p: string): string {
  return path.relative(guildDir, p);
}

/** Read the existing v2 settings.json (object) if present + parseable. */
function readSettings(fs: Fs, p: string): Record<string, unknown> {
  if (!fs.existsSync(p)) return {};
  const res = parseJson(fs.readFileSync(p));
  return res.ok && res.value && typeof res.value === "object"
    ? (res.value as Record<string, unknown>)
    : {};
}

/** Read a possibly-dotted key value out of a parsed config object. */
function readKeyValue(parsed: Record<string, unknown>, dotted: string): unknown {
  if (dotted in parsed) return parsed[dotted];
  return getPath(parsed, dotted);
}

/**
 * Remove a v1 key (possibly dotted) from a config object.
 *
 * Handles two representations of a dotted key (P2 literal-dotted-key fix):
 *   1. Literal top-level key: `{ "wiki.share_mode": "private" }` — YAML that
 *      was written with a literal dot in the key name (not nested). Removed via
 *      `delete obj[dotted]` first.
 *   2. Nested path: `{ wiki: { share_mode: "private" } }` — the more typical
 *      YAML nesting. Removed by descending the split path.
 * Both may co-exist (unusual but possible), so both are always attempted.
 */
function stripKey(obj: Record<string, unknown>, dotted: string): void {
  // (1) Literal top-level dotted key (e.g. "wiki.share_mode" stored verbatim).
  if (dotted in obj) delete obj[dotted];

  // (2) Nested path (the canonical nested representation).
  const parts = dotted.split(".");
  if (parts.length === 1) return; // already handled above
  let cur: unknown = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (cur && typeof cur === "object" && parts[i] in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[parts[i]];
    } else {
      return;
    }
  }
  if (cur && typeof cur === "object") delete (cur as Record<string, unknown>)[parts[parts.length - 1]];
}

/**
 * Main convert entry — iterates the §2 rows that produce action. carry-forward
 * rows are not visited (they need no work); the report records them separately if
 * desired, but the converter touches only convert/preserve+flag artifacts.
 */
export function convert(
  fs: Fs,
  clock: Clock,
  guildDir: string,
  dryRun: boolean,
  snapshotRef: string
): ConvertOutput {
  const out: ConvertOutput = { artifacts: [], relocated: [], conflicts: [], removed: [], generated: [] };
  const ctx: Ctx = { fs, clock, guildDir, dryRun, snapshotRef, out };
  const j = (r: string) => path.join(guildDir, r);

  const settingsPath = j("settings.json");
  const v2Settings = readSettings(fs, settingsPath);
  let settingsMutated = false;

  // ── Row: config.yml → settings.json (+ .unmigrated-v1.json) ───────────────
  {
    const p = j("config.yml");
    if (fs.existsSync(p)) {
      const res = parseYaml(fs.readFileSync(p));
      if (!res.ok || !res.value || typeof res.value !== "object") {
        // Should not happen (corrupt would have blocked), but be safe: preserve+flag.
        out.artifacts.push({
          rel: rel(guildDir, p),
          disposition: "preserve+flag",
          note: "config.yml unparseable at convert time — preserved",
        });
      } else {
        const parsed = res.value as Record<string, unknown>;
        const v1Keys = v1KeysIn(parsed);
        // config.yml may also carry mappable-but-not-"v1-only" keys (loops/loop_cap/
        // codex_cap) — those are C1 carry-into-settings if absent in v2.
        const carryKeys = ["loops", "loop_cap", "codex_cap"].filter((k) => k in parsed);
        const allKeys = [...new Set([...v1Keys, ...carryKeys])];
        const { outcomes, mutated } = convertSurfaceWithCarry(
          ctx,
          rel(guildDir, p),
          parsed,
          v2Settings,
          allKeys
        );
        if (mutated) settingsMutated = true;
        // Any remaining key in config.yml with no v2 home + not handled ⇒ C2 relocate.
        for (const k of Object.keys(parsed)) {
          if (allKeys.includes(k)) continue;
          const cls = classifyKey(k, parsed[k], v2Settings);
          outcomes.push(cls.outcome);
          if (cls.relocate)
            out.relocated.push({ source: rel(guildDir, p), key: k, value: parsed[k], reason: "unmapped" });
          if (cls.outcome.case === "C4") out.conflicts.push(cls.outcome);
        }
        const anyC4 = outcomes.some((o) => o.case === "C4");
        const sourceRemovable = !anyC4;
        out.artifacts.push({
          rel: rel(guildDir, p),
          disposition: anyC4 ? "preserve+flag" : "convert",
          target: "settings.json",
          keys: outcomes,
          note: anyC4
            ? "C4 conflict — config.yml kept LIVE, tree stays mixed, re-surface next open"
            : "converted to settings.json; removed from live (snapshot holds original)",
          removed: sourceRemovable,
        });
        if (sourceRemovable && !dryRun) {
          fs.rmFileSync(p);
        }
        if (sourceRemovable) out.removed.push(rel(guildDir, p));
      }
    }
  }

  // ── Row: project.yaml wiki.share_mode → settings.json defaults.wiki.share_mode
  {
    const p = j("project.yaml");
    if (fs.existsSync(p)) {
      const res = parseYaml(fs.readFileSync(p));
      if (res.ok && res.value && typeof res.value === "object") {
        const parsed = res.value as Record<string, unknown>;
        const shareVal = readKeyValue(parsed, "wiki.share_mode");
        if (shareVal !== undefined) {
          const cls = classifyKey("wiki.share_mode", shareVal, v2Settings);
          const outcomes = [cls.outcome];
          if (cls.write) {
            setPath(v2Settings, cls.write.v2Key, cls.write.v2Value);
            settingsMutated = true;
          }
          const isC4 = cls.outcome.case === "C4";
          if (isC4) out.conflicts.push(cls.outcome);
          // project.yaml is identity-bearing — NEVER removed; only the migrated key
          // is stripped (C1/C3). On C4 the key stays LIVE.
          if (!isC4 && !dryRun) {
            stripKey(parsed, "wiki.share_mode");
            fs.writeFileSync(p, serializeYaml(parsed));
          }
          out.artifacts.push({
            rel: rel(guildDir, p),
            disposition: isC4 ? "preserve+flag" : "convert",
            target: "settings.json:defaults.wiki.share_mode",
            keys: outcomes,
            note: isC4
              ? "C4 share_mode conflict — wiki.share_mode kept LIVE in project.yaml, settings.json NOT clobbered, re-surface"
              : cls.outcome.case === "C3"
                ? "redundant share_mode dropped from project.yaml (settings.json authoritative)"
                : "wiki.share_mode moved to settings.json; key removed from project.yaml",
            removed: false,
          });
        }
      }
    }
  }

  // ── Row: settings.json carrying a stray v1 key (hand-mixed) ───────────────
  convertV2SurfaceInPlace(ctx, settingsPath, v2Settings, (mut) => {
    if (mut) settingsMutated = true;
  });

  // ── Row: settings.local.json carrying a v1 key (P9 / CF-W1b-7) ────────────
  {
    const p = j("settings.local.json");
    if (fs.existsSync(p)) {
      const res = parseJson(fs.readFileSync(p));
      if (res.ok && res.value && typeof res.value === "object") {
        const parsed = res.value as Record<string, unknown>;
        const v1Keys = v1KeysIn(parsed);
        if (v1Keys.length > 0) {
          const outcomes: KeyOutcome[] = [];
          let anyC4 = false;
          let localMutated = false;
          for (const k of v1Keys) {
            const value = readKeyValue(parsed, k);
            // settings.local.json is a v2-era IN-PLACE override surface. A same-name
            // alias (e.g. auto_approve string) must transform in-place (C1/C3), NOT be
            // compared cross-file against settings.json and stuck C4. Pass inPlace=true
            // so classifyKey skips the v2Target lookup for same-name aliases.
            // Different-name aliases (e.g. defaults.agent_team → agent_mode) still use
            // v2Settings as the target for the existence/conflict check, which is correct:
            // the v2 key (agent_mode) lives in settings.json, not in the local file.
            const cls = classifyKey(k, value, v2Settings, /*inPlace=*/true);
            outcomes.push(cls.outcome);
            if (cls.write) {
              // Rewrite in place in the local file (it is a v2 surface).
              // Same-name alias guard (P2 fix): if v1Key === v2Key, the write IS
              // the in-place replace — do NOT strip (that would delete the new value).
              setPath(parsed, cls.write.v2Key, cls.write.v2Value);
              if (cls.write.v1Key !== cls.write.v2Key) stripKey(parsed, k);
              localMutated = true;
            } else if (cls.relocate) {
              out.relocated.push({ source: rel(guildDir, p), key: k, value, reason: "unmapped" });
              stripKey(parsed, k);
              localMutated = true;
            } else if (cls.outcome.case === "C3") {
              stripKey(parsed, k);
              localMutated = true;
            } else if (cls.outcome.case === "C4") {
              anyC4 = true;
              out.conflicts.push(cls.outcome);
              // C4 — key STAYS LIVE; do not strip.
            }
          }
          if (localMutated && !dryRun) fs.writeFileSync(p, JSON.stringify(parsed, null, 2) + "\n");
          out.artifacts.push({
            rel: rel(guildDir, p),
            disposition: anyC4 ? "preserve+flag" : "convert",
            keys: outcomes,
            note: anyC4
              ? "C4 conflict — deprecated alias kept LIVE in settings.local.json, re-surface"
              : "v1 keys migrated in place (file is a v2 surface; stays)",
            removed: false,
          });
        }
      }
    }
  }

  // ── Row: runs/<id>/metadata.json (no run.yaml) → run.yaml + provenance.json
  convertLegacyRuns(ctx);

  // ── Persist settings.json once (single write) ─────────────────────────────
  if (settingsMutated && !dryRun) {
    const settingsIsNew = !fs.existsSync(settingsPath);
    fs.writeFileSync(settingsPath, JSON.stringify(v2Settings, null, 2) + "\n");
    // Track as generated only if it didn't exist before this migration run
    // (otherwise the snapshot already holds it and the restore overwrites it).
    if (settingsIsNew) out.generated.push(rel(guildDir, settingsPath));
  }

  // ── Write the shared .unmigrated-v1.json ─────────────────────────────────
  // Merge with any EXISTING .unmigrated-v1.json from a prior partial migration
  // (never clobber). Deduplicate by (source, key) so a repeated run with an
  // unresolved C4+C2 source does not accumulate duplicate entries. (P3 fix.)
  if (out.relocated.length > 0 && !dryRun) {
    const unmigratedPath = j(".unmigrated-v1.json");
    const isNew = !fs.existsSync(unmigratedPath);
    let mergedEntries: UnmigratedEntry[] = [];
    if (!isNew) {
      const existing = parseJson(fs.readFileSync(unmigratedPath));
      if (existing.ok && existing.value && typeof existing.value === "object") {
        const prior = (existing.value as Record<string, unknown>)["entries"];
        if (Array.isArray(prior)) mergedEntries = prior as UnmigratedEntry[];
      }
    }
    // UPSERT by (source, key): if the identity already exists in the prior entries,
    // REPLACE its value with the current run's (newer) value — the user may have
    // edited the source between runs while a C4 kept it live. If the identity is
    // new, append it. This gives no-duplicate AND latest-value-wins semantics. (P2b fix.)
    const indexMap = new Map(mergedEntries.map((e, i) => [`${e.source}\0${e.key}`, i]));
    for (const entry of out.relocated) {
      const id = `${entry.source}\0${entry.key}`;
      const existing = indexMap.get(id);
      if (existing !== undefined) {
        // Replace with current run's entry (newer value wins).
        mergedEntries[existing] = entry;
      } else {
        indexMap.set(id, mergedEntries.length);
        mergedEntries.push(entry);
      }
    }
    const doc = buildUnmigratedDoc(clock.iso(), snapshotRef, mergedEntries);
    fs.writeFileSync(unmigratedPath, doc);
    if (isNew) out.generated.push(rel(guildDir, unmigratedPath));
  }

  return out;
}

/**
 * Convert a config surface that mixes v1-only keys AND carry-keys (loops/loop_cap/
 * codex_cap). carry-keys are C1 into settings.json when absent, C3 when equal,
 * C4 when differing.
 */
function convertSurfaceWithCarry(
  ctx: Ctx,
  sourceRel: string,
  parsed: Record<string, unknown>,
  v2Target: Record<string, unknown>,
  keys: string[]
): { outcomes: KeyOutcome[]; mutated: boolean } {
  const outcomes: KeyOutcome[] = [];
  let mutated = false;
  for (const k of keys) {
    const value = readKeyValue(parsed, k);
    // carry-keys (loops/loop_cap/codex_cap) map to the SAME key name in v2.
    if (k === "loops" || k === "loop_cap" || k === "codex_cap") {
      const existing = getPath(v2Target, k);
      if (existing === undefined) {
        setPath(v2Target, k, normalizeCarry(k, value));
        mutated = true;
        outcomes.push({ key: k, case: "C1", detail: `${k}=${JSON.stringify(normalizeCarry(k, value))}` });
      } else if (valueEqual(existing, normalizeCarry(k, value))) {
        outcomes.push({ key: k, case: "C3", detail: `${k} redundant (already ${JSON.stringify(existing)})` });
      } else {
        outcomes.push({ key: k, case: "C4", detail: `${k} conflict: v2=${JSON.stringify(existing)} vs v1=${JSON.stringify(value)}` });
        ctx.out.conflicts.push(outcomes[outcomes.length - 1]);
      }
      continue;
    }
    const cls = classifyKey(k, value, v2Target);
    outcomes.push(cls.outcome);
    if (cls.write) {
      setPath(v2Target, cls.write.v2Key, cls.write.v2Value);
      mutated = true;
    }
    if (cls.relocate)
      ctx.out.relocated.push({ source: sourceRel, key: cls.relocate.key, value: cls.relocate.value, reason: "unmapped" });
    if (cls.outcome.case === "C4") {
      ctx.out.conflicts.push(cls.outcome);
    }
  }
  return { outcomes, mutated };
}

function normalizeCarry(k: string, v: unknown): unknown {
  if (k === "loop_cap" && typeof v === "number") return Math.min(256, Math.max(1, v));
  if (k === "codex_cap" && typeof v === "number") return Math.min(10, Math.max(1, v));
  return v;
}

/**
 * A v2 surface file (settings.json / settings.local.json) that carries a stray v1
 * key: rewrite in place to v2 form (C1), drop redundant (C3), relocate unmapped
 * (C2), keep C4 live.
 *
 * SAME-NAME ALIAS handling (P2 fix — auto_approve string→array):
 * When v1Key === v2Key (the transform keeps the same key name but changes the VALUE
 * shape, e.g. auto_approve "spec-and-plan" → ["spec","plan"]), the "existing" v2
 * value IS the v1 value — there is no separate v2 counterpart to conflict with. In
 * this case we always do an in-place replace (C1: write the transformed v2 value in
 * place, do NOT strip the key afterward since stripping would delete what we just
 * wrote). We never compare a same-name alias against itself for a C4 — a C4 can
 * only arise when v1Key !== v2Key and a DIFFERENT key already holds a v2 value.
 */
function convertV2SurfaceInPlace(
  ctx: Ctx,
  p: string,
  v2Obj: Record<string, unknown>,
  onMutate: (mutated: boolean) => void
): void {
  if (!ctx.fs.existsSync(p)) return;
  const v1Keys = v1KeysIn(v2Obj);
  if (v1Keys.length === 0) return;
  const outcomes: KeyOutcome[] = [];
  let anyC4 = false;
  let mutated = false;
  for (const k of v1Keys) {
    const value = readKeyValue(v2Obj, k);
    const mapped = mapV1Key(k, value);
    if (!mapped) {
      ctx.out.relocated.push({ source: rel(ctx.guildDir, p), key: k, value, reason: "unmapped" });
      stripKey(v2Obj, k);
      mutated = true;
      outcomes.push({ key: k, case: "C2", detail: `relocated verbatim (${JSON.stringify(value)})` });
      continue;
    }
    // Same-name alias (v1Key === v2Key): the current value IS the v1 form —
    // no separate counterpart exists. Always C1 (transform in place); never C4.
    if (mapped.v1Key === mapped.v2Key) {
      // The value is already the transformed form iff valueEqual (C3), else C1.
      if (valueEqual(value, mapped.v2Value)) {
        // C3: value is already in the correct v2 shape — nothing to do.
        outcomes.push({ key: k, case: "C3", detail: `${k} already in v2 form ${JSON.stringify(value)}` });
      } else {
        // C1: replace in place (do NOT strip — v1Key === v2Key; stripping drops the value).
        setPath(v2Obj, mapped.v2Key, mapped.v2Value);
        mutated = true;
        outcomes.push({ key: k, case: "C1", detail: `${k} transformed in-place → ${JSON.stringify(mapped.v2Value)}` });
      }
      continue;
    }
    // Different-name mapping: check for a pre-existing v2 counterpart.
    const existing = getPath(v2Obj, mapped.v2Key);
    if (existing === undefined) {
      setPath(v2Obj, mapped.v2Key, mapped.v2Value);
      stripKey(v2Obj, k);
      mutated = true;
      outcomes.push({ key: k, case: "C1", detail: `${k} → ${mapped.v2Key}=${JSON.stringify(mapped.v2Value)}` });
    } else if (valueEqual(existing, mapped.v2Value)) {
      stripKey(v2Obj, k);
      mutated = true;
      outcomes.push({ key: k, case: "C3", detail: `redundant: ${mapped.v2Key} already ${JSON.stringify(existing)}` });
    } else {
      anyC4 = true;
      outcomes.push({
        key: k,
        case: "C4",
        detail: `CONFLICT: ${mapped.v2Key}=${JSON.stringify(existing)} vs v1 ${k}=${JSON.stringify(value)} → kept LIVE`,
      });
      ctx.out.conflicts.push(outcomes[outcomes.length - 1]);
    }
  }
  onMutate(mutated);
  ctx.out.artifacts.push({
    rel: rel(ctx.guildDir, p),
    disposition: anyC4 ? "preserve+flag" : "convert",
    keys: outcomes,
    note: anyC4
      ? "C4 stray-key conflict — v1 key kept LIVE in settings.json, re-surface"
      : "stray v1 key(s) rewritten in place to v2 form",
    removed: false,
  });
}

/**
 * runs/<id>/metadata.json (no sibling run.yaml) → reconstruct run.yaml +
 * provenance.json. If fields are insufficient → preserve+flag (CF-W1b-4: do NOT
 * fabricate). events.ndjson is carry-forward (CF-W1b-3).
 */
function convertLegacyRuns(ctx: Ctx): void {
  const { fs, guildDir, dryRun } = ctx;
  const runsDir = path.join(guildDir, "runs");
  if (!fs.existsSync(runsDir)) return;
  let entries;
  try {
    entries = fs.readdirSync(runsDir);
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isDirectory) continue;
    const runDir = path.join(runsDir, e.name);
    const meta = path.join(runDir, "metadata.json");
    const runYaml = path.join(runDir, "run.yaml");
    if (!fs.existsSync(meta) || fs.existsSync(runYaml)) continue;
    const res = parseJson(fs.readFileSync(meta));
    if (!res.ok || !res.value || typeof res.value !== "object") {
      ctx.out.artifacts.push({
        rel: rel(guildDir, meta),
        disposition: "preserve+flag",
        note: "metadata.json unparseable — preserved",
        removed: false,
      });
      continue;
    }
    const m = res.value as Record<string, unknown>;
    const runId = (m["run_id"] ?? m["id"] ?? e.name) as string;
    const createdAt = (m["created_at"] ?? m["started_at"]) as string | undefined;
    // Minimal faithfulness check (CF-W1b-4): need at least a run id + a timestamp.
    if (!runId || !createdAt) {
      ctx.out.artifacts.push({
        rel: rel(guildDir, meta),
        disposition: "preserve+flag",
        note: "insufficient fields to reconstruct a faithful run.yaml — preserved (NOT fabricated)",
        removed: false,
      });
      continue;
    }
    const provPath = path.join(runDir, "provenance.json");
    const provExists = fs.existsSync(provPath);

    const runDoc =
      `schema_version: guild.run.v1\n` +
      `run_id: ${runId}\n` +
      `created_at: ${createdAt}\n` +
      (m["initiative"] ? `initiative: ${m["initiative"]}\n` : "") +
      (m["status"] ? `status: ${m["status"]}\n` : "");

    // Run-level C4 analog: if provenance.json already exists (an existing v2
    // artifact), this is a genuine conflict — keep metadata.json LIVE (never write
    // run.yaml, never delete metadata.json) and re-surface next open. Writing
    // run.yaml + deleting metadata.json while provenance.json exists would silently
    // "resolve" the conflict without user action, leaving the tree with a fabricated
    // run.yaml and no way to re-surface. (P2 fix — round-2 correction.)
    if (provExists) {
      ctx.out.artifacts.push({
        rel: rel(guildDir, meta),
        disposition: "preserve+flag",
        note: `run-level conflict: provenance.json already exists — metadata.json kept LIVE, run.yaml NOT written, re-surface next open`,
        removed: false,
      });
      // Nothing written, nothing removed. Source stays live; detection re-fires P6
      // on the next open so the conflict re-surfaces correctly.
      continue;
    }

    const provDoc = {
      schema_version: "guild.provenance.v1",
      run_id: runId,
      created_at: createdAt,
      reconstructed_from: "metadata.json",
      ...("status" in m ? { status: m["status"] } : {}),
    };
    if (!dryRun) {
      fs.writeFileSync(runYaml, runDoc);
      fs.writeFileSync(provPath, JSON.stringify(provDoc, null, 2) + "\n");
      ctx.out.generated.push(rel(guildDir, runYaml));
      ctx.out.generated.push(rel(guildDir, provPath));
      fs.rmFileSync(meta);
    }
    ctx.out.removed.push(rel(guildDir, meta));
    ctx.out.artifacts.push({
      rel: rel(guildDir, meta),
      disposition: "convert",
      target: `runs/${e.name}/run.yaml + provenance.json`,
      note: "legacy metadata.json → run.yaml/provenance reconstructed; metadata.json moved to snapshot",
      removed: true,
    });
  }
}

/**
 * Minimal YAML serializer for the flat project.yaml shape we re-write (after
 * stripping wiki.share_mode). Uses js-yaml via seams to stay lossless for the
 * shapes we touch.
 */
function serializeYaml(obj: Record<string, unknown>): string {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const yaml = require("js-yaml") as { dump(o: unknown): string };
  return yaml.dump(obj);
}
