/**
 * scripts/__tests__/config-schema-resolver-parity.test.ts
 *
 * THE INERT-KEY GUARD — a class rail, not a lane test.
 *
 * Guild's config surface is consumed through THREE closed key sets:
 *
 *   1. `CONFIG_SCHEMA` (scripts/lib/config-schema.ts), generated by flattening the
 *      canonical DEFAULTS tree — what `config init`, `reconcile`, the UI metadata and
 *      `validate` all read;
 *   2. `RESOLVER_TIER1_KEYS` + `ResolvedConfig` (src/modules/config/workflows/
 *      settings-reader.ts), the resolver's OWN closed key set — what every RUNTIME
 *      consumer reads through `settings-resolver`;
 *   3. `SETTINGS_JSON_KNOWN_KEYS`, the protected-surface guard's accepted settings
 *      shape — what umbrella CI permits in a changed `.guild/settings.json`.
 *
 * This is the C5 multi-home problem WITHOUT a sync script: closed sets can drift
 * silently unless this rail binds them. S5's `capability` block was registered in
 * the schema, the CLI loader, the UI metadata AND the persist matrix — 33 green tests —
 * but not in the resolver, so a project setting `capability.resolver_mode: "strict"`
 * resolved to the shipped default. Config that cannot be read is config that does not
 * exist; the feature was inert at runtime while every test passed.
 *
 * ANTI-VACUITY: this rail is not decorative. Run it against the tree immediately before
 * commit 6d35498's resolver fix and it FAILS with `capability` present in the schema and
 * absent from the resolver — which is precisely the defect it now prevents.
 *
 * If a future lane adds a top-level config key, this test tells it — at CI time rather
 * than in production — that registering the key in the schema is only half the job.
 */

import { CONFIG_SCHEMA } from "../lib/config-schema";
import { RESOLVER_TIER1_KEYS, resolveSettings } from "../lib/settings-resolver";
import { DEFAULTS } from "../lib/shared/config-defaults";
import { SETTINGS_JSON_KNOWN_KEYS } from "../comms/no-accidental-write";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

/** The distinct FIRST segments of every flattened schema key. */
function schemaTopLevelKeys(): Set<string> {
  return new Set(CONFIG_SCHEMA.map((spec) => spec.key.split(".")[0]));
}

describe("config surface parity — CONFIG_SCHEMA vs the runtime resolver", () => {
  it("every schema top-level key is READABLE by the resolver (no inert keys)", () => {
    const schemaKeys = [...schemaTopLevelKeys()].sort();
    const missing = schemaKeys.filter((key) => !RESOLVER_TIER1_KEYS.has(key));
    // A key here is one a project can CONFIGURE and the runtime will silently IGNORE.
    expect(missing).toEqual([]);
  });

  it("the resolver accepts no key the schema does not define (no orphan keys)", () => {
    const schemaKeys = schemaTopLevelKeys();
    const orphans = [...RESOLVER_TIER1_KEYS].filter((key) => !schemaKeys.has(key)).sort();
    // A key here is one the resolver reads but `config init`/`reconcile` never writes
    // and `validate` does not know — undocumented surface.
    expect(orphans).toEqual([]);
  });

  it("the two sets are EXACTLY equal", () => {
    expect([...RESOLVER_TIER1_KEYS].sort()).toEqual([...schemaTopLevelKeys()].sort());
  });

  it("the protected-surface guard accepts exactly the resolver's top-level keys", () => {
    expect([...SETTINGS_JSON_KNOWN_KEYS].sort()).toEqual([...RESOLVER_TIER1_KEYS].sort());
  });

  it("ANTI-VACUITY: both sets are non-empty and cover the known surface", () => {
    // Without this, two empty sets would satisfy every assertion above.
    expect(RESOLVER_TIER1_KEYS.size).toBeGreaterThan(20);
    expect(schemaTopLevelKeys().size).toBe(RESOLVER_TIER1_KEYS.size);
    // Spot-check a few keys from different eras so an accidental wholesale truncation
    // of either set cannot pass.
    for (const key of ["rigor", "models", "defaults", "host_mode", "capability"]) {
      expect(RESOLVER_TIER1_KEYS.has(key)).toBe(true);
      expect(schemaTopLevelKeys().has(key)).toBe(true);
    }
  });

  it("every top-level key also exists on the canonical DEFAULTS tree", () => {
    // The third corner of the triangle: DEFAULTS is what CONFIG_SCHEMA is generated
    // FROM, so a key present in both sets but absent from DEFAULTS would mean the
    // generator and the resolver agree on something that has no default.
    for (const key of schemaTopLevelKeys()) {
      expect(Object.prototype.hasOwnProperty.call(DEFAULTS, key)).toBe(true);
    }
  });
});

describe("config surface parity — the property the key sets stand in for", () => {
  // The set comparison above is a proxy. THIS is the behavior that actually matters:
  // a value written to settings.json must survive resolution. Proven end-to-end for
  // the key this lane added, because that is the one that was inert.
  function resolveWith(settings: Record<string, unknown>) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cfg-parity-"));
    fs.mkdirSync(path.join(dir, ".guild"), { recursive: true });
    fs.writeFileSync(path.join(dir, ".guild", "settings.json"), JSON.stringify(settings));
    return resolveSettings({ cwd: dir });
  }

  it("a configured value survives resolution rather than reverting to the default", () => {
    const resolved = resolveWith({ capability: { resolver_mode: "strict" } });
    expect(resolved.config.capability?.resolver_mode).toBe("strict");
    // And the control: an unset block resolves to the shipped default.
    expect(resolveWith({}).config.capability?.resolver_mode).toBe(
      DEFAULTS.capability.resolver_mode,
    );
  });

  it("a configured 0 survives — falsy values are the classic silent-drop case", () => {
    expect(resolveWith({ capability: { suggestion_budget: 0 } }).config.capability?.suggestion_budget).toBe(0);
  });
});
