/**
 * hooks/__tests__/bypass-forcing.test.ts
 *
 * D-BYPASS autonomy-mode forcing (docs/v2/security.md §bypassPermissions
 * governance): under `auto_approve` / `autonomous_after_plan_approval` the
 * `bypass_permissions_policy` is FORCED to `deny` — a bypassPermissions
 * attempt on an out-of-scope call hard-blocks (abort + security event).
 * Interactive mode keeps the configured policy (default `audit`).
 *
 * Covers:
 *   - effectiveBypassPolicy() pure matrix (both non-interactive modes force
 *     deny over every configured value; interactive passes through).
 *   - resolveScopeDecision() forced-deny reason + gate.
 *   - resolveRunAutonomyMode() against REAL artifacts: a guild.task_run.v1
 *     file generated by the REAL scripts/write-task-run.ts CLI (no
 *     hand-authored fixture — generated-shape discipline), the settings
 *     `defaults.gates.auto_approve` layer, the env layer, and the
 *     interactive default.
 */

import { spawnSync } from "child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

import {
  parseAutonomyMode,
  resolveRunAutonomyMode,
  type AutonomyMode,
  type BypassPolicy,
} from "../lib/security/config";
import { effectiveBypassPolicy, resolveScopeDecision } from "../lib/security/enforce";

const WRITE_TASK_RUN = path.resolve(__dirname, "../../scripts/write-task-run.ts");

describe("effectiveBypassPolicy — autonomy-mode forcing matrix", () => {
  const configured: BypassPolicy[] = ["deny", "audit", "allow"];

  it.each(configured)(
    "auto_approve forces deny over configured %s",
    (policy) => {
      const r = effectiveBypassPolicy(policy, "auto_approve");
      expect(r.policy).toBe("deny");
      expect(r.forced).toBe(true);
    },
  );

  it.each(configured)(
    "autonomous_after_plan_approval forces deny over configured %s",
    (policy) => {
      const r = effectiveBypassPolicy(policy, "autonomous_after_plan_approval");
      expect(r.policy).toBe("deny");
      expect(r.forced).toBe(true);
    },
  );

  it.each(configured)("interactive passes through configured %s", (policy) => {
    const r = effectiveBypassPolicy(policy, "interactive");
    expect(r.policy).toBe(policy);
    expect(r.forced).toBe(false);
  });
});

describe("resolveScopeDecision — forced deny under bypassPermissions", () => {
  const scope = { capability: ["Read"], autonomy: null, invalid: false };

  it("hard-blocks (deny) with a forcing reason when policyForced", () => {
    const d = resolveScopeDecision({
      scope,
      toolName: "Bash",
      toolInput: { command: "curl http://evil" },
      policy: "deny",
      permissionMode: "bypassPermissions",
      policyForced: true,
    });
    expect(d.gate).toBe(true);
    expect(d.permissionDecision).toBe("deny");
    expect(d.recordedDecision).toBe("deny");
    expect(d.eventType).toBe("capability_scope_violation");
    expect(d.reason).toContain("FORCED by non-interactive autonomy");
  });

  it("interactive (not forced): audit proceeds but records the violation", () => {
    const d = resolveScopeDecision({
      scope,
      toolName: "Bash",
      toolInput: { command: "curl http://evil" },
      policy: "audit",
      permissionMode: "bypassPermissions",
      policyForced: false,
    });
    expect(d.gate).toBe(false);
    expect(d.recordedDecision).toBe("allow");
    expect(d.eventType).toBe("capability_scope_violation");
  });
});

describe("parseAutonomyMode — closed triple", () => {
  it("accepts exactly the three modes", () => {
    expect(parseAutonomyMode("interactive")).toBe("interactive");
    expect(parseAutonomyMode("auto_approve")).toBe("auto_approve");
    expect(parseAutonomyMode("autonomous_after_plan_approval")).toBe(
      "autonomous_after_plan_approval",
    );
  });
  it("rejects anything else", () => {
    expect(parseAutonomyMode("yolo")).toBeNull();
    expect(parseAutonomyMode("")).toBeNull();
    expect(parseAutonomyMode(undefined)).toBeNull();
    expect(parseAutonomyMode(42)).toBeNull();
  });
});

describe("resolveRunAutonomyMode — layered resolution against real artifacts", () => {
  let tmp: string;
  const RUN = "run-bypass-test";
  const TASK = "T1";

  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), "guild-bypass-mode-"));
    fs.mkdirSync(path.join(tmp, ".guild", "runs", RUN), { recursive: true });
  });
  afterEach(() => fs.rmSync(tmp, { recursive: true, force: true }));

  /** Generate the task_run file with the REAL writer CLI (generated shape). */
  function writeRealTaskRun(autonomyPolicy: AutonomyMode): void {
    const r = spawnSync(
      "npx",
      [
        "tsx",
        WRITE_TASK_RUN,
        "--cwd",
        tmp,
        "--run-id",
        RUN,
        "--task-id",
        TASK,
        "--specialist",
        "backend",
        "--objective",
        "bypass forcing test",
        "--autonomy-policy",
        autonomyPolicy,
      ],
      { encoding: "utf8", timeout: 60000 },
    );
    expect(r.status).toBe(0);
    expect(
      fs.existsSync(path.join(tmp, ".guild", "runs", RUN, "task-runs", `${TASK}.yaml`)),
    ).toBe(true);
  }

  it("layer 1: env GUILD_AUTONOMY_POLICY wins outright", () => {
    expect(
      resolveRunAutonomyMode({
        cwd: tmp,
        env: { GUILD_AUTONOMY_POLICY: "auto_approve" },
      }),
    ).toBe("auto_approve");
  });

  it("layer 2: reads autonomy_policy from the REAL guild.task_run.v1 file (auto_approve)", () => {
    writeRealTaskRun("auto_approve");
    expect(
      resolveRunAutonomyMode({
        cwd: tmp,
        env: { GUILD_RUN_ID: RUN, GUILD_TASK_ID: TASK },
      }),
    ).toBe("auto_approve");
  });

  it("layer 2: reads autonomous_after_plan_approval from the REAL task_run file", () => {
    writeRealTaskRun("autonomous_after_plan_approval");
    expect(
      resolveRunAutonomyMode({
        cwd: tmp,
        env: { GUILD_RUN_ID: RUN, GUILD_TASK_ID: TASK },
      }),
    ).toBe("autonomous_after_plan_approval");
  });

  it("layer 3: defaults.gates.auto_approve non-empty in settings.json ⇒ auto_approve", () => {
    fs.writeFileSync(
      path.join(tmp, ".guild", "settings.json"),
      JSON.stringify({ defaults: { gates: { auto_approve: ["all"] } } }),
      "utf8",
    );
    expect(resolveRunAutonomyMode({ cwd: tmp, env: {} })).toBe("auto_approve");
  });

  it("layer 4: defaults to interactive when nothing declares a mode", () => {
    expect(resolveRunAutonomyMode({ cwd: tmp, env: {} })).toBe("interactive");
  });

  it("unsafe run/task ids never reach the filesystem layer (fail to interactive)", () => {
    expect(
      resolveRunAutonomyMode({
        cwd: tmp,
        env: { GUILD_RUN_ID: "../escape", GUILD_TASK_ID: TASK },
      }),
    ).toBe("interactive");
  });
});
