/**
 * Backward-compatible public entrypoint.
 *
 * The task-cell backend contract is dispatch-domain code (T12 fold, KTD36).
 */

export {
  isTerminal,
  canTransition,
  assertTransition,
  leadBinding,
  attemptLineage,
  taskCellPaths,
  assertWithinRunTree,
  buildTaskAssignmentV2,
  validateTaskAssignmentV2,
  validateAgentInstanceV1,
  validateTaskAttemptV1,
  assignmentId,
  outOfScopeFiles,
  releasedLogicalTasks,
  dependencyGate,
  isHeartbeatStale,
  reconstructCellState,
  TASK_CELL_STATES,
  type TaskCellState,
  TERMINAL_STATES,
  type TerminalState,
  LEGAL_TRANSITIONS,
  IllegalTransitionError,
  type CellFanout,
  type TaskCellSubstrate,
  type ModelTier,
  type TaskCellBudgets,
  type LeadBinding,
  type AttemptLineage,
  AGENT_INSTANCE_SCHEMA,
  type AgentInstanceV1,
  TASK_ATTEMPT_SCHEMA,
  type TaskAttemptV1,
  TASK_ASSIGNMENT_V2_SCHEMA,
  type ToolPermissionProjection,
  type AssignmentDependency,
  type AssignmentChannels,
  type TaskAssignmentV2Base,
  type TaskAssignmentV2,
  type TaskCellPathIds,
  type TaskCellPaths,
  type BuildTaskAssignmentInput,
  type SubmittedHandoff,
  HANDOFF_VALIDATION_SCHEMA,
  type HandoffValidationV1,
  ACCEPTANCE_AUTHORITIES,
  type AcceptanceAuthority,
  type AuthorityDecision,
  HANDOFF_ACCEPTANCE_SCHEMA,
  type HandoffAcceptanceV1,
  type DependencyGateResult,
  type CellHandle,
  type InstanceHandle,
  type InstanceRef,
  type TaskCellFailure,
  type OpFailure,
  type SpawnCellRequest,
  type SpawnInstanceRequest,
  type AwaitReadyResult,
  type DeliverAssignmentResult,
  type AwaitAssignmentAckResult,
  type InstanceObservation,
  type HeartbeatResult,
  type CollectHandoffResult,
  type AcceptHandoffRequest,
  type AcceptHandoffResult,
  type RejectHandoffRequest,
  type RejectHandoffResult,
  type TerminalOutcome,
  type TerminateRequest,
  type TerminateResult,
  type AwaitTerminatedResult,
  type ReapResult,
  type WaitOptions,
  type TaskCellRecordSet,
  type TaskCellRecordStore,
  type TaskCellBackend,
  type ReconstructedAttempt,
  type ReconstructedCell,
} from "../../../../src/domains/dispatch/index";
